export const CREATE_PLACELIST_ERROR = 'CREATE_PLACELIST_ERROR';
export const CREATE_PLACELIST_SUCCESS = 'CREATE_PLACELIST_SUCCESS';

export const DELETE_PLACELIST_ERROR = 'DELETE_PLACELIST_ERROR';
export const DELETE_PLACELIST_SUCCESS = 'DELETE_PLACELIST_SUCCESS';

export const UNDELETE_PLACELIST_ERROR = 'UNDELETE_PLACELIST_ERROR';

export const UPDATE_PLACELIST_ERROR = 'UPDATE_PLACELIST_ERROR';
export const UPDATE_PLACELIST_SUCCESS = 'UPDATE_PLACELIST_SUCCESS';

export const FILTER_PLACELISTS = 'FILTER_PLACELISTS';
export const LOAD_PLACELISTS_SUCCESS = 'LOAD_PLACELISTS_SUCCESS';
export const UNLOAD_PLACELISTS_SUCCESS = 'UNLOAD_PLACELISTS_SUCCESS';
